# https://guides.github.com/features/pages/

theme: jekyll-theme-dinky
title: Product Delivery Ingredients
description: Ingredients that can potentially help make product delivery successful
markdown: kramdown
